---
--- Generated by Luanalysis
--- Created by boluo.
--- DateTime: 2023/12/20 17:49
---

local key = KEYS[1];
local argsValue = cjson.decode(ARGV[1]);
local redisValue = redis.call('get', key);

if not argsValue then return end
if redisValue then
    local redisServiceArr = (cjson.decode(redisValue))['value'];
    for k, v in ipairs(redisServiceArr) do
        if v['port'] .. v['domain'] == argsValue['port'] .. argsValue['domain'] then
            table.remove(redisServiceArr, k);
            break;
        end
    end
    redis.call('set', key, cjson.encode({ value = redisServiceArr }));
end